title: Abigail Plummer
logo: /assets/img/abigailplummer.jpg
description: "" #I am a physics PhD student at Harvard University studying soft matter.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

