title: Abigail Plummer
logo: /assets/img/abigailplummer.jpg
description: Abigail Plummer. Postdoc at Princeton studying soft matter.
show_downloads: true
google_analytics: UA-172525780-1
theme: jekyll-theme-minimal

